In [1]:
import numpy

In [4]:
import my_file

200


In [5]:
import keyword as kw

In [6]:
from keyword import kwlist, iskeyword

In [7]:
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [8]:
import numpy as np

In [9]:
a=np.array([])

In [10]:
a

array([], dtype=float64)

In [11]:
b=np.array([3,4,5,8,6])

In [12]:
len(b)

5

In [13]:
b.size

5

In [14]:
b.ndim

1

In [15]:
a.ndim

1

In [16]:
c=np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,9]])

In [17]:
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [18]:
c.shape

(4, 3)

In [19]:
d=np.array([[[2],[3],[4]],[[4],[5],[6]],[[7],[8],[9]],[[10],[11],[9]]])

In [20]:
d


array([[[ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [ 9]]])

In [22]:
d.shape

(4, 3, 1)

In [23]:
c[0][1]

3

In [24]:
c[0:2,-1]

array([4, 6])